server:
  port: 1000
spring:
  application:
    name: atguigu-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
  instance:
    instance-id: consumer
    prefer-ip-address: true
